// Code generated by \"mapconst -type=TradeState,CapitalFlowType\"; DO NOT EDIT"

package front

var TradeStateNameToValue = map[string]TradeState{
	"UNKNOWN":    UNKNOWN,
	"NOTPAY":     NOTPAY,
	"SUCCESS":    SUCCESS,
	"REFUND":     REFUND,
	"CLOSED":     CLOSED,
	"REVOKED":    REVOKED,
	"USERPAYING": USERPAYING,
	"PAYERROR":   PAYERROR,
}

var CapitalFlowTypeNameToValue = map[string]CapitalFlowType{
	"TCapitalFlowUnknown":    TCapitalFlowUnknown,
	"TCapitalFlowPrepay":     TCapitalFlowPrepay,
	"TCapitalFlowPrepayBack": TCapitalFlowPrepayBack,
	"TCapitalFlowTrade":      TCapitalFlowTrade,
	"TCapitalFlowRefund":     TCapitalFlowRefund,
	"TCapitalFlowWithdraw":   TCapitalFlowWithdraw,
}
