// Code generated by \"const_list -type=TradeState,CapitalFlowType\"; DO NOT EDIT"

package front

func TradeStateList() []TradeState {
	return []TradeState{UNKNOWN, NOTPAY, SUCCESS, REFUND, CLOSED, REVOKED, USERPAYING, PAYERROR}
}

func CapitalFlowTypeList() []CapitalFlowType {
	return []CapitalFlowType{TCapitalFlowUnknown, TCapitalFlowPrepay, TCapitalFlowPrepayBack, TCapitalFlowTrade, TCapitalFlowRefund, TCapitalFlowWithdraw}
}
